### ISSUE TITLE
Swap node feature request

### ISSUE THREAD

**Issue by jrj2211** [wooorm/linked-list#19]
I'd like to request that a swap function is built into the library. Looking at dozens of linked list implementations on NPM none of them have a swap function.

Below is the code I'm using for swapping nodes. Theres a lot of references that need to be updated with a swap and many use cases such as being neighbors, or tail/head. From what I tell this code works for all those use cases but I haven't done extensive testing on it.

```
swap(item1, item2) {
    const temp1 = {prev: item1.prev, cur: item1, next: item1.next};
    const temp2 = {prev: item2.prev, cur: item2, next: item2.next};

    // Same node do nothing
    if(item1 === item2) {
      return;
    }

    // Update head
    if(item1 === this.head) {
      this.head = item2;
    } else if(item2 === this.head) {
      this.head = item1;
    }

    // Update tail
    if(item1 === this.tail) {
      this.tail = item2;
    } else if(item2 === this.tail) {
      this.tail = item1;
    }

    // Swap item1
    this.swapItems(item1, 'next', temp2);
    this.swapItems(item1, 'prev', temp2);

    // Swap item2
    this.swapItems(item2, 'next', temp1);
    this.swapItems(item2, 'prev', temp1);
  }

  swapItems(item, position, swap) {
    if(item !== swap[position]) {
      // Items are not neighbors
      item[position] = swap[position];
      if(item[position]) {
        // Update surrounding nodes
        if(position === 'next') {
          item[position].prev = item;
        } else if(position === 'prev') {
          item[position].next = item;
        }
      }
    } else {
      // Items are neighbors
      item[position] = swap.cur;
    }
  }
```

Heres a visualization of this code to show it can swap any positions and a use case for this feature:

![RSidJY4k1Q](https://user-images.githubusercontent.com/6005836/128082957-ad7c8daf-4feb-470e-8964-0e4ce5a6530a.gif)

**Comment by wooorm** [comment]
Thanks for your patience! Cool visualization :)

I might be open to such a feature if you’re interested in working on it. But, as you say, most libraries don’t have it. To me that indicates that it’s not used a lot. So I’m also fine in keeping this in userland and hence I’ll close this.

It could also be added to the dcos here (lists and items can also be subclassed to add such features, that makes it optional rather than a feature that every user of this library gets).
If this feature was added, perhaps to the docs only, then it should come with types and tests and docs!
